/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp tokolosh.xml -a tokolosh_adaptor -c MediaAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TOKOLOSH_ADAPTOR_H_1239555810
#define TOKOLOSH_ADAPTOR_H_1239555810

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.TokoloshXineBackend.TokoloshMediaPlayer
 */
class MediaAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.TokoloshXineBackend.TokoloshMediaPlayer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.TokoloshXineBackend.TokoloshMediaPlayer\" >\n"
"    <method name=\"play\" />\n"
"    <method name=\"stop\" />\n"
"    <method name=\"prev\" />\n"
"    <method name=\"next\" />\n"
"    <method name=\"pause\" />\n"
"    <method name=\"clearLibraryPaths\" />\n"
"    <method name=\"repopulateLibrary\" />\n"
"    <method name=\"toggleMute\" />\n"
"    <method name=\"toggleShuffle\" />\n"
"    <method name=\"toggleRepeat\" />\n"
"    <method name=\"syncClients\" />\n"
"    <method name=\"dumpFiles\" />\n"
"    <signal name=\"crashed\" />\n"
"    <method name=\"shuffle\" >\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\" />\n"
"    </method>\n"
"    <method name=\"repeat\" >\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\" />\n"
"    </method>\n"
"    <method name=\"volume\" >\n"
"      <arg direction=\"out\" type=\"i\" name=\"volume\" />\n"
"    </method>\n"
"    <method name=\"setVolume\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"volume\" />\n"
"    </method>\n"
"    <method name=\"load\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\" />\n"
"    </method>\n"
"    <signal name=\"trackChanged\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"path\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    MediaAdaptor(QObject *parent);
    virtual ~MediaAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void clearLibraryPaths();
    void dumpFiles();
    void load(const QString &path);
    void next();
    void pause();
    void play();
    void prev();
    bool repeat();
    void repopulateLibrary();
    void setVolume(int volume);
    bool shuffle();
    void stop();
    void syncClients();
    void toggleMute();
    void toggleRepeat();
    void toggleShuffle();
    int volume();
Q_SIGNALS: // SIGNALS
    void crashed();
    void trackChanged(const QString &path);
};

#endif
