/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -c TokoloshInterface -p tokolosh_interface.h:tokolosh_interface.cpp ../tokolosh/tokolosh.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "tokolosh_interface.h"

/*
 * Implementation of interface class TokoloshInterface
 */

TokoloshInterface::TokoloshInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

TokoloshInterface::~TokoloshInterface()
{
}

