#############################################################################
# Makefile for building: tokolosh
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Apr 12 17:03:28 2009
# Project:  tokolosh.pro
# Template: subdirs
# Command: /void/dev/qt/sdk/200901/qt/bin/qmake -unix -o Makefile tokolosh.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /void/dev/qt/sdk/200901/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-tokoloshhead \
		sub-tokoloshtail

tokoloshhead/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tokoloshhead/ || $(MKDIR) tokoloshhead/ 
	cd tokoloshhead/ && $(QMAKE) tokoloshhead.pro -unix -o $(MAKEFILE)
sub-tokoloshhead-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tokoloshhead/ || $(MKDIR) tokoloshhead/ 
	cd tokoloshhead/ && $(QMAKE) tokoloshhead.pro -unix -o $(MAKEFILE)
sub-tokoloshhead: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE)
sub-tokoloshhead-make_default: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) 
sub-tokoloshhead-make_first: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) first
sub-tokoloshhead-all: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) all
sub-tokoloshhead-clean: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) clean
sub-tokoloshhead-distclean: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tokoloshhead-install_subtargets: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) install
sub-tokoloshhead-uninstall_subtargets: tokoloshhead/$(MAKEFILE) FORCE
	cd tokoloshhead/ && $(MAKE) -f $(MAKEFILE) uninstall
tokoloshtail/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tokoloshtail/ || $(MKDIR) tokoloshtail/ 
	cd tokoloshtail/ && $(QMAKE) tokoloshtail.pro -unix -o $(MAKEFILE)
sub-tokoloshtail-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tokoloshtail/ || $(MKDIR) tokoloshtail/ 
	cd tokoloshtail/ && $(QMAKE) tokoloshtail.pro -unix -o $(MAKEFILE)
sub-tokoloshtail: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE)
sub-tokoloshtail-make_default: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) 
sub-tokoloshtail-make_first: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) first
sub-tokoloshtail-all: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) all
sub-tokoloshtail-clean: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) clean
sub-tokoloshtail-distclean: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tokoloshtail-install_subtargets: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) install
sub-tokoloshtail-uninstall_subtargets: tokoloshtail/$(MAKEFILE) FORCE
	cd tokoloshtail/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: tokolosh.pro  ../qt/sdk/200901/qt/mkspecs/linux-g++-64/qmake.conf ../qt/sdk/200901/qt/mkspecs/common/g++.conf \
		../qt/sdk/200901/qt/mkspecs/common/unix.conf \
		../qt/sdk/200901/qt/mkspecs/common/linux.conf \
		../qt/sdk/200901/qt/mkspecs/qconfig.pri \
		../qt/sdk/200901/qt/mkspecs/features/qt_functions.prf \
		../qt/sdk/200901/qt/mkspecs/features/qt_config.prf \
		../qt/sdk/200901/qt/mkspecs/features/exclusive_builds.prf \
		../qt/sdk/200901/qt/mkspecs/features/default_pre.prf \
		../qt/sdk/200901/qt/mkspecs/features/release.prf \
		../qt/sdk/200901/qt/mkspecs/features/default_post.prf \
		../qt/sdk/200901/qt/mkspecs/features/warn_on.prf \
		../qt/sdk/200901/qt/mkspecs/features/qt.prf \
		../qt/sdk/200901/qt/mkspecs/features/unix/thread.prf \
		../qt/sdk/200901/qt/mkspecs/features/moc.prf \
		../qt/sdk/200901/qt/mkspecs/features/resources.prf \
		../qt/sdk/200901/qt/mkspecs/features/uic.prf \
		../qt/sdk/200901/qt/mkspecs/features/yacc.prf \
		../qt/sdk/200901/qt/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile tokolosh.pro
../qt/sdk/200901/qt/mkspecs/common/g++.conf:
../qt/sdk/200901/qt/mkspecs/common/unix.conf:
../qt/sdk/200901/qt/mkspecs/common/linux.conf:
../qt/sdk/200901/qt/mkspecs/qconfig.pri:
../qt/sdk/200901/qt/mkspecs/features/qt_functions.prf:
../qt/sdk/200901/qt/mkspecs/features/qt_config.prf:
../qt/sdk/200901/qt/mkspecs/features/exclusive_builds.prf:
../qt/sdk/200901/qt/mkspecs/features/default_pre.prf:
../qt/sdk/200901/qt/mkspecs/features/release.prf:
../qt/sdk/200901/qt/mkspecs/features/default_post.prf:
../qt/sdk/200901/qt/mkspecs/features/warn_on.prf:
../qt/sdk/200901/qt/mkspecs/features/qt.prf:
../qt/sdk/200901/qt/mkspecs/features/unix/thread.prf:
../qt/sdk/200901/qt/mkspecs/features/moc.prf:
../qt/sdk/200901/qt/mkspecs/features/resources.prf:
../qt/sdk/200901/qt/mkspecs/features/uic.prf:
../qt/sdk/200901/qt/mkspecs/features/yacc.prf:
../qt/sdk/200901/qt/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile tokolosh.pro

qmake_all: sub-tokoloshhead-qmake_all sub-tokoloshtail-qmake_all FORCE

make_default: sub-tokoloshhead-make_default sub-tokoloshtail-make_default FORCE
make_first: sub-tokoloshhead-make_first sub-tokoloshtail-make_first FORCE
all: sub-tokoloshhead-all sub-tokoloshtail-all FORCE
clean: sub-tokoloshhead-clean sub-tokoloshtail-clean FORCE
distclean: sub-tokoloshhead-distclean sub-tokoloshtail-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-tokoloshhead-install_subtargets sub-tokoloshtail-install_subtargets FORCE
uninstall_subtargets: sub-tokoloshhead-uninstall_subtargets sub-tokoloshtail-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

